@BASE_URL=http://localhost:5000

#####################################
### 1. Welcome
#####################################
GET {{BASE_URL}}/

#####################################
### 2. Register
#####################################
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
  "email": "oo@hotmail.com",
  "username": "oo",
  "password": "123456"
}

#####################################
### 3. Login (IMPORTANT)
#####################################
# @name login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
  "email": "GG@hotmail.com",
  "password": "123456"
}

#####################################
### 4. Save Token
#####################################
@token = {{login.response.body.token}}

#####################################
### 5. Get Orders (ADMIN ONLY)
#####################################
GET {{BASE_URL}}/orders
Authorization: Bearer {{token}}