@BASE_URL=http://localhost:5000

### TEST ORDER
POST {{BASE_URL}}/orders
Content-Type: application/json

{
  "user_id": 1
}


### CREATE ORDER
POST {{BASE_URL}}/api/orders
Content-Type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJHZyIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzc0OTQ4Njk2LCJleHAiOjE3NzUwMzUwOTZ9.iLfZfAJQT5B88USUD5XGm53PgKSH77gRxLd17vwl8BQ

{
  "user_id": 1,
  "totalPrice": 240,
  "items": [
    {
      "cakeId": 8,
      "quantity": 2
    }
  ]
}