@BASE_URL = http://localhost:5000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJCZXN0Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzc0MzIzOTc2LCJleHAiOjE3NzQ0MTAzNzZ9.3pl2OuE-4sTWZDOy_8H9EzvBNOGiBM7RnmoHM2cuqU8

### get me
GET {{BASE_URL}}/users/me
Authorization: Bearer {{token}}


### edit me
PUT {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "Best",
  "password": "123456"
}
